name = "slack-zenn-rss-tracker"
main = "src/index.ts"
compatibility_date = "2023-12-06"

kv_namespaces = [
  { binding = "KV", id = "c7809edca7b54b00a21ec6def4460ab7" }
]

[triggers]
crons = ["* * * * *"] # * * * * * = run every minute
